alias g='git'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gcl='git clone'
alias gco='git checkout'
alias gd='git diff'
alias gl='git pull --ff-only'
alias glg='git log --oneline --decorate --graph --all'
alias gp='git push'
alias grs='git restore'
alias gst='git status -sb'
alias gsw='git switch'

