name: "📚 Documentation or README.md issue report"
description: "Report an issue in the project's documentation or README.md file."
title: " "
labels:
  - "Type: Doc"

body:
  - type: markdown
    attributes:
      value:  "**🐞 Bug Report | 📚 Documentation or README.md issue report**"

  - type: textarea
    attributes:
      label: "Describe the bug"
      description: A clear and concise description of what the bug is.
      placeholder: When using this specific feature, the application crashes.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Repro steps
      description: Steps to reproduce the behavior. If you can, please provide a [Minimal and Reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Clicking the button should send my request.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: How often does this bug happen?
      description: How easily can you reproduce this bug?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once
    validations:
      required: true
  - type: textarea
    attributes:
      label: System info
      description: Add any relevant system information here, such as the operating system, the browser, the version, etc.
      placeholder: |
        - Operating System: macOS 12.4
        - Browser: Chrome
        - Version: v2.1.0
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about your issue.
