name: 🚀🆕 Feature request
description: Suggest an idea.
title: " Feature : "
labels:
  - "Type: Feature"
body:
  - type: markdown
    attributes:
      value: 🚀🆕 Feature request
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when '…'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Clicking this button should do the thing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I thought about adding a new menu to do the thing, but '…'
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
