name: 📑 Story
description: Story for the Feature/ Enhancements
title: " Story : "
labels:
  - "Type: Story"
body:
  - type: markdown
    attributes:
      value:  📑 Story
  - type: textarea
    attributes:
      label: Story
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when '…'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Task List
      description: A clear and concise description of what you want to happen.
      placeholder: "- [] task 1"
    validations:
      required: true
