name: ✍🏼  Task
description: Task for the task
title: " ✍🏼 Task : "
labels:
  - "Type: Task"
body:
  - type: markdown
    attributes:
      value:  ✍🏼  Task
  - type: textarea
    attributes:
      label: Task
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when '…'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Task List
      description: A clear and concise description of what you want to happen.
      placeholder: "- [] task 1"
    validations:
      required: true
