# blank_issues_enabled: false
# contact_links:
#     name: Send an e-mail to the developer
#     url: mailto:rbmalik1994@gmail.com
#     about: Please do NOT use this email to post issues or feature requests (only important business/personal contact).
